import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return(
  <nav className="flex items-center justify-between w-full border-b p-4 text-xl font-semibold">
    <div>Gallery</div>
    <div>Sign In</div>
  </nav>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`flex flex-col gap-4 ${GeistSans.variable}`} >
      <body>
        <TopNav/>
        {/* <div className="w-full">First line</div> */}
        {children}
      </body>
    </html>
  );
}
